global:
  scrape_interval: "5s"

scrape_configs:
  - job_name: "elastic-sniffer"
    static_configs:
            - targets: ["elasticsearch_exporter:9114"]
  
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "application"
    static_configs:
      - targets: ["api:1002", "consumer:1001", "producer:1000"]