{
 "title": "Estudos",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Aplicação",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "p99 tempo de processamento de eventos",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(events_process_time_bucket{instance=\"consumer:1001\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historico de tempo de processamento de evento",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(events_process_time_bucket{instance=\"consumer:1001\"}[5m]))",
     "legendFormat": "Tempo"
    }
   ]
  },
  {
   "title": "p99 tempo de resposta endpoints API",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{instance=\"api:1002\", endpoint=\"/eventos_db/\"}[5m]))",
     "legendFormat": "{{p99 DataBase}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{instance=\"api:1002\", endpoint=\"/eventos_es/\"}[5m]))",
     "legendFormat": "{{P99 ElasticSearch}}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Eventos offset",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset{topic=\"eventos_clientes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Lag Kafka",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{consumergroup=\"Estudos\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}